auth {
    pam {
        module = password-auth
    }

    fingerprint {
        enabled = true
    }
}

background {
    monitor =
    path = $HOME/Pictures/wallpaper/0000.jpg
    blur_size = 2
    blur_passes = 1
    noise = 0.01
    contrast = 1.08
    brightness = 0.68
    vibrancy = 0.22
    vibrancy_darkness = 0.15
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(9DEBFF)
    font_size = 104
    font_family = Noto Sans Mono
    position = 0, 230
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 10
    shadow_color = rgba(00D9FF55)
}

shape {
    monitor =
    size = 460, 2
    color = rgb(00D9FF)
    position = 0, 152
    halign = center
    valign = center
}

shape {
    monitor =
    size = 110, 2
    color = rgb(FF2A9D)
    position = 285, 152
    halign = center
    valign = center
}

label {
    monitor =
    text = // $USER
    color = rgb(FF5CB8)
    font_size = 18
    font_family = Noto Sans Mono
    position = 0, 112
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 7
    shadow_color = rgba(FF2A9D66)
}

input-field {
    monitor =
    size = 340, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(00D9FF)
    inner_color = rgba(3, 7, 18, 0.82)
    font_color = rgb(FF5CB8)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text =
    hide_input = false
    rounding = 4
    check_color = rgb(FF2A9D)
    fail_color = rgb(FF2A9D)
    fail_text =
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below
    position = 0, -35
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 10
    shadow_color = rgba(00D9FF55)
}
